services:
  - name: vaultwarden
    build:
      dockerfilePath: ./Dockerfile
    env:
      ROCKET_PORT: 80
      ADMIN_TOKEN: $(vaultwarden hash $(openssl rand -base64 32))
      DOMAIN: ${RAILWAY_STATIC_URL}
      I_REALLY_WANT_VOLATILE_STORAGE: "false"
    startCommand: "./start.sh"
    volumes:
      - path: /data
