services:
  - name: vaultwarden
    build:
      dockerfilePath: ./Dockerfile
    env:
      ROCKET_PORT: 80
      ADMIN_TOKEN: $(vaultwarden hash $(openssl rand -base64 32))
    startCommand: "./start.sh"
    volumes:
      - path: /data
